import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vault",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="[--header-height:4rem]">
        <SidebarProvider className="flex flex-col">
          <Header />
          <div className="flex flex-1 overflow-hidden">
            <AppSidebar />
            <SidebarInset className="mt-16">{children}</SidebarInset>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
